apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: simple-app-py
spec:
  hostnames:
  - example.com
  parentRefs:
  - name: traefik # Gateway must exist with configured listener
    namespace: traefik
  rules:
  - backendRefs:
    - name: simple-app-py
      port: 80
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          replacePrefixMatch: /
          type: ReplacePrefixMatch
    matches:
    - path:
        type: PathPrefix
        value: /env_1
