apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patches:
- path: httproute-patch.yaml
  target:
    kind: HTTPRoute
    name: simple-app-py
images:
- name: ghcr.io/gitopolis/simple-app-py
  newName: ghcr.io/gitopolis/simple-app-py
  newTag: sha-53a6ba3
